### ISSUE TITLE
Enforce internal max code length

### ISSUE THREAD

**Issue by zongweil** [curbmap/OpenLocationCode-swift#4]
Hello!

I'm one of the OLC maintainers and we are in the process of updating all the implementations to limit the number of digits processed to avoid underflow errors. Take a look at https://github.com/google/open-location-code/issues/190 for more details and examples.

Is this something you would be able to take care of for your implementation?

**Comment by eselkin** [comment]
Yes. Will do right now. Also, will update the project to swift 4.2. I've been meaning to.

**Comment by zongweil** [comment]
Thanks for the quick action! I added a couple of comments on your commit - happy to continue the discussion.

**Comment by eselkin** [comment]
Should be complete in 0.5.5 (including the comment changes :-) )

**Comment by zongweil** [comment]
Thanks! :)

**Comment by fulldecent** [comment]
This is fixed here https://github.com/curbmap/OpenLocationCode-swift/commit/ccc5a0a0b572f82c9ae4da8dc65fd81d5b972eb0 and already released
